/**
 * Project Euler #2: Even Fibonacci numbers
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1  and  2, the first  terms will be:
 * 1,2,3,5,8,13,21,34,55,89,...
 * *
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.
 */

class Euler002(val n: Int) {
    fun solution(): Int {
        if (n < 2) return 0
        var buffer = 1
        var current = 1
        var count = 0
        while (current < n) {
            val temp = current + buffer
            if (temp < n && temp % 2 == 0) {
                count += temp
            }
            buffer = current
            current = temp
        }
        return count
    }
}

fun main(args: Array<String>) {
    val n = 100000
    val result = Euler002(n).solution();
    print("sum even number from 1 to %d result is %d".format(n, result))
}
