"""
Project Euler #2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.

"""

def solution(n):
    if n < 2:
        return 0
    buffer = 1
    current = 1
    count = 0
    while current < n:
        temp = current + buffer
        if temp % 2 == 0 and temp < n:
            count += temp
        buffer = current
        current = temp
    return count


if __name__ == '__main__':
    print(solution(100))
